version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Evyde
      POSTGRES_PASSWORD: a8ec19ec-a6c9-40d5-86ea-d776c7a6ebb8
      POSTGRES_DB: SpringBook
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
